import {
  bgColors,
  black,
  brandColors,
  breakpoints,
  buttonHeights,
  controlColors,
  fontColors,
  fontFamily,
  fontWeights,
  grey,
  grid,
  iconSizes,
  iconStroke,
  letterSpacings,
  lineColors,
  radii,
  shadows,
  spacingScale,
  statusColors,
  typography,
} from './tokens'

export const palettes = {
  light: {
    background: bgColors.white,
    text: fontColors.black,
    body: fontColors.sub,
    soft: grey[700],
    muted: fontColors.info,
    faint: fontColors.disabled,
    border: lineColors.regular,
    divider: lineColors.light,
    surface: bgColors.light,
    accent: brandColors.main,
    link: brandColors.sub1,
    danger: statusColors.error,
    pill: 'rgba(255, 255, 255, 0.85)',
    card: '#FFFFFF',
    accentHover: controlColors.brandHover,
    accentPress: controlColors.brandPress,
    controlGray: controlColors.grayBg,
    controlGrayHover: controlColors.grayHover,
    controlGrayPress: controlColors.grayPress,
    controlDisabled: controlColors.disabled,
    dangerHover: '#D32F2F',
    dangerPress: '#C62828',
    focusBorder: controlColors.focusBorder,
    focusRing: controlColors.focusRing,
    badgeSuccessBg: '#E8F5E9',
    badgeSuccessText: '#2E7D32',
    badgeDangerBg: '#FFEBEE',
    badgeDangerText: '#C62828',
    badgeWarningBg: '#FFF8E1',
    badgeWarningText: '#F57F17',
    badgeInfoBg: '#E3F2FD',
    badgeInfoText: '#1565C0',
    badgeNeutralBg: '#F1F1F5',
    badgeNeutralText: '#505050',
  },
  dark: {
    background: bgColors.black,
    text: '#FFFFFF',
    body: grey[300],
    soft: grey[400],
    muted: grey[500],
    faint: grey[600],
    border: black[300],
    divider: black[500],
    surface: black[650],
    accent: '#448AFF',
    link: '#A78BFA',
    danger: '#FF5252',
    pill: 'rgba(28, 28, 28, 0.75)',
    card: black[650],
    accentHover: '#2962FF',
    accentPress: '#1E54EA',
    controlGray: black[550],
    controlGrayHover: black[450],
    controlGrayPress: black[400],
    controlDisabled: black[250],
    dangerHover: '#E53935',
    dangerPress: '#D32F2F',
    focusBorder: '#448AFF',
    focusRing: 'rgba(68, 138, 255, 0.45)',
    badgeSuccessBg: 'rgba(67, 160, 71, 0.16)',
    badgeSuccessText: '#81C784',
    badgeDangerBg: 'rgba(229, 57, 53, 0.16)',
    badgeDangerText: '#EF9A9A',
    badgeWarningBg: 'rgba(249, 168, 37, 0.16)',
    badgeWarningText: '#FFD54F',
    badgeInfoBg: 'rgba(41, 98, 255, 0.16)',
    badgeInfoText: '#90CAF9',
    badgeNeutralBg: black[500],
    badgeNeutralText: grey[400],
  },
} as const

export const theme = {
  colors: {
    background: 'var(--c-background)',
    text: 'var(--c-text)',
    body: 'var(--c-body)',
    soft: 'var(--c-soft)',
    muted: 'var(--c-muted)',
    faint: 'var(--c-faint)',
    border: 'var(--c-border)',
    divider: 'var(--c-divider)',
    surface: 'var(--c-surface)',
    accent: 'var(--c-accent)',
    link: 'var(--c-link)',
    danger: 'var(--c-danger)',
    pill: 'var(--c-pill)',
    card: 'var(--c-card)',
    accentHover: 'var(--c-accentHover)',
    accentPress: 'var(--c-accentPress)',
    controlGray: 'var(--c-controlGray)',
    controlGrayHover: 'var(--c-controlGrayHover)',
    controlGrayPress: 'var(--c-controlGrayPress)',
    controlDisabled: 'var(--c-controlDisabled)',
    dangerHover: 'var(--c-dangerHover)',
    dangerPress: 'var(--c-dangerPress)',
    focusBorder: 'var(--c-focusBorder)',
    focusRing: 'var(--c-focusRing)',
    badgeSuccessBg: 'var(--c-badgeSuccessBg)',
    badgeSuccessText: 'var(--c-badgeSuccessText)',
    badgeDangerBg: 'var(--c-badgeDangerBg)',
    badgeDangerText: 'var(--c-badgeDangerText)',
    badgeWarningBg: 'var(--c-badgeWarningBg)',
    badgeWarningText: 'var(--c-badgeWarningText)',
    badgeInfoBg: 'var(--c-badgeInfoBg)',
    badgeInfoText: 'var(--c-badgeInfoText)',
    badgeNeutralBg: 'var(--c-badgeNeutralBg)',
    badgeNeutralText: 'var(--c-badgeNeutralText)',
  },
  fonts: {
    base: fontFamily,
  },
  fontWeights,
  letterSpacings,
  typography,
  spacing: spacingScale,
  radii,
  shadows,
  layout: {
    maxWidth: '680px',
    grid,
  },
  breakpoints,
  controls: {
    buttonHeights,
    iconSizes,
    iconStroke,
  },
} as const

export type AppTheme = typeof theme

declare module '@emotion/react' {
  export interface Theme extends AppTheme {}
}
